#program to print unique number from user given number
s=set()
num=input("Enter number 1:")
s.add(int(num))
num=input("Enter number 2:")
s.add(int(num))
num=input("Enter number 3:")
s.add(int(num))
num=input("Enter number 4:")
s.add(int(num))
num=input("Enter number 5:")
s.add(int(num))
num=input("Enter number 6:")
s.add(int(num))
num=input("Enter number 7:")
s.add(int(num))
num=input("Enter number 8:")
s.add(int(num))
print("\n",s)

